Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:
a) Addition of 2 in all the element
b) Multiply 3 with all the elements
c) Divide every element by 2

In [13]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr_add = arr + 2
print("Addition of 2:\n", arr_add)
arr_mul = arr * 3
print("\nMultiplication by 3:\n", arr_mul)
arr_div = arr / 2
print("\nDivision by 2:\n", arr_div)

Addition of 2:
 [3 4 5 6 7]

Multiplication by 3:
 [ 3  6  9 12 15]

Division by 2:
 [0.5 1.  1.5 2.  2.5]


Q.2 Questions on Basic NumPy Array:
a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
b) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [12]:
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = np.flip(arr)
print("Reversed array:\n", reversed_arr)
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
values, counts = np.unique(x, return_counts=True)
most_frequent_value_x = values[np.argmax(counts)]
indices_x = np.where(x == most_frequent_value_x)
print("\nMost frequent value in x:", most_frequent_value_x)
print("Indices of most frequent value in x:", indices_x)
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
values, counts = np.unique(y, return_counts=True)
most_frequent_value_y = values[np.argmax(counts)]
indices_y = np.where(y == most_frequent_value_y)
print("\nMost frequent value in y:", most_frequent_value_y)
print("Indices of most frequent value in y:", indices_y)


Reversed array:
 [5 4 6 3 2 1]

Most frequent value in x: 1
Indices of most frequent value in x: (array([0, 5, 7, 8, 9]),)

Most frequent value in y: 1
Indices of most frequent value in y: (array([0, 1, 2]),)


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:
a) Access 1st row, 2nd column
b) Access 3rd row, 1st column


In [11]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
element_a = arr[0, 1]
print("Element at 1st row, 2nd column:", element_a)

element_b = arr[2, 0]
print("Element at 3rd row, 1st column:", element_b)

Element at 1st row, 2nd column: 20
Element at 3rd row, 1st column: 70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [9]:
import numpy as np
my_array = np.linspace(10, 100, 25)
print("Dimensions:", my_array.ndim)
print("Shape:", my_array.shape)
print("Total elements:", my_array.size)
print("Data type:", my_array.dtype)
print("Total bytes:", my_array.nbytes)
transposed_array_reshape = my_array.reshape(25,1)
print("\nTranspose using reshape:\n", transposed_array_reshape)
transposed_array_t = my_array.T
print("\nTranspose using .T:\n", transposed_array_t)

Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200

Transpose using reshape:
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Transpose using .T:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>.


In [10]:
ucs420_your_name = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])
mean = np.mean(ucs420_your_name)
median = np.median(ucs420_your_name)
max_val = np.max(ucs420_your_name)
min_val = np.min(ucs420_your_name)
unique_elements = np.unique(ucs420_your_name)
print("Mean:", mean)
print("Median:", median)
print("Max:", max_val)
print("Min:", min_val)
print("Unique elements:", unique_elements)
reshaped_ucs420_your_name = ucs420_your_name.reshape(4, 3)
print("\nReshaped array:\n", reshaped_ucs420_your_name)
resized_ucs420_your_name = np.resize(ucs420_your_name, (2, 3))
print("\nResized array:\n", resized_ucs420_your_name)


Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized array:
 [[10 20 30]
 [40 50 60]]
